ServiceMonitor.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceMonitor.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Service Dashboard";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ServiceMonitor.Web/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceMonitor.BL;
using ServiceMonitor.Entity.Model;

namespace ServiceMonitor.Web.Controllers
{
    public class NotificationController : Controller
    {
        // GET: Service
        public ActionResult _Notification(int id, string callback)
        {
            return PartialView(id);
        }

        public ActionResult _Add(int id, string callback)
        {
            ViewBag.Callback = callback;
            var service = new Notification{ServiceId = id};
            return PartialView(service);
        }

        public ActionResult _Edit(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new NotificationMgt().GetById(id));
        }

        public ActionResult _Delete(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new NotificationMgt().GetById(id));
        }
    }
}

ServiceMonitor.Web/Controllers/NotificationMethodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services.Description;
using ServiceMonitor.BL;
using Notification = ServiceMonitor.Entity.Model.Notification;

namespace ServiceMonitor.Web.Controllers
{
    public class NotificationMethodsController : ApiController
    {
        public HttpResponseMessage GetAll()
        {
            var items = new NotificationMethodMgt().GetAll();
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, items);
        }

    }
}

ServiceMonitor.Web/Controllers/NotificationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services.Description;
using ServiceMonitor.BL;
using Notification = ServiceMonitor.Entity.Model.Notification;

namespace ServiceMonitor.Web.Controllers
{
    public class NotificationTypesController : ApiController
    {
        public HttpResponseMessage GetAll()
        {
            var items = new NotificationTypeMgt().GetAll();
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, items);
        }

    }
}

ServiceMonitor.Web/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services.Description;
using ServiceMonitor.BL;
using Notification = ServiceMonitor.Entity.Model.Notification;

namespace ServiceMonitor.Web.Controllers
{
    public class NotificationsController : ApiController
    {
        public HttpResponseMessage Get(int id)
        {
            var items = new NotificationMgt().GetByServiceId(id);
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, items);
        }

        public HttpResponseMessage Delete(int? Id)
        {
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, new NotificationMgt().Delete(new Notification
            {
                Id = Id.Value
            }));
        }

        public Notification Post(Notification item)
        {
            return new NotificationMgt().Add(item);
        }

        public Notification Put(Notification item)
        {
            return new NotificationMgt().Update(item);

        }
    }
}

ServiceMonitor.Web/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceMonitor.BL;
using ServiceMonitor.Entity.Model;

namespace ServiceMonitor.Web.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _Add(string callback)
        {
            ViewBag.Callback = callback;
            var service = new Service();
            return PartialView(service);
        }

        public ActionResult _Edit(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new ServiceMgt().GetById(id));
        }

        public ActionResult _Delete(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new ServiceMgt().GetById(id));
        }
    }
}

ServiceMonitor.Web/Controllers/ServiceOutageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceMonitor.BL;
using ServiceMonitor.Entity.Model;

namespace ServiceMonitor.Web.Controllers
{
    public class ServiceOutageController : Controller
    {
        // GET: Service
        public ActionResult _ServiceOutage(int id, string callback)
        {
            return PartialView(id);
        }

        public ActionResult _Add(int id, string callback)
        {
            ViewBag.Callback = callback;
            var service = new ServiceOutage{ServiceId = id};
            return PartialView(service);
        }

        public ActionResult _Edit(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new ServiceOutageMgt().GetById(id));
        }

        public ActionResult _Delete(int id, string callback)
        {
            ViewBag.Callback = callback;
            return PartialView(new ServiceOutageMgt().GetById(id));
        }
    }
}

ServiceMonitor.Web/Controllers/ServiceOutagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services.Description;
using ServiceMonitor.BL;
using ServiceOutage = ServiceMonitor.Entity.Model.ServiceOutage;

namespace ServiceMonitor.Web.Controllers
{
    public class ServiceOutagesController : ApiController
    {
        public HttpResponseMessage Get(int id)
        {
            var items = new ServiceOutageMgt().GetByServiceId(id);
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, items);
        }

        public HttpResponseMessage Delete(int? Id)
        {
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, new ServiceOutageMgt().Delete(new ServiceOutage
            {
                Id = Id.Value
            }));
        }

        public ServiceOutage Post(ServiceOutage item)
        {
            return new ServiceOutageMgt().Add(item);
        }

        public ServiceOutage Put(ServiceOutage item)
        {
            return new ServiceOutageMgt().Update(item);

        }
    }
}

ServiceMonitor.Web/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services.Description;
using ServiceMonitor.BL;
using Service = ServiceMonitor.Entity.Model.Service;

namespace ServiceMonitor.Web.Controllers
{
    public class ServicesController : ApiController
    {
        public HttpResponseMessage GetAllWithDetails()
        {
            var items = new ServiceMgt().GetAllWithDetails();
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, new { items });
        }

        public HttpResponseMessage GetAll()
        {
            var items = new ServiceMgt().GetAll();
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, items);
        }

        public HttpResponseMessage Delete(int? Id)
        {
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, new ServiceMgt().Delete(new Service
            {
                Id = Id.Value
            }));
        }

        public Service Post(Service item)
        {
            return new ServiceMgt().Add(item);
        }

        public Service Put(Service item)
        {
            return new ServiceMgt().Update(item);

        }
    }
}

ServiceMonitor.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ServiceMonitor.Web/Views/Notification/_Edit.cshtml
<div id="edit-notification-@Model.Id">
    <div class="form-wrapper">
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-4 col-xs-12">Notification Type</label>
            <div class="col-md-8 col-xs-12">
                <input id="dd-SurveyId" data-role="dropdownlist"
                       data-auto-bind="false"
                       data-value-primitive="true"
                       data-text-field="Name"
                       data-value-field="Id"
                       data-bind="value: NotificationTypeId, source: notificationTypes"
                       style="width: 100%;" tabindex="1" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-4 col-xs-12">Notification Method</label>
            <div class="col-md-8 col-xs-12">
                <input id="dd-SurveyId" data-role="dropdownlist"
                       data-auto-bind="false"
                       data-value-primitive="true"
                       data-text-field="Name"
                       data-value-field="Id"
                       data-bind="value: NotificationMethodId, source: notificationMethods"
                       style="width: 100%;" tabindex="1" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Contact Data</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: ContactData" class="k-textbox" />
            </div>
        </div>
        <div class="row form-footer">
            <div>
                @Html.Action("_Delete", "Notification", new { id = Model.Id, callback = ViewBag.Callback })
                <button class="k-button k-button-icontext" data-bind="events={click:editNotification@(Model.Id)}"><span class="k-icon k-i-save"></span>Update</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
        var editNotificationModel@(Model.Id) = kendo.observable(@(Html.Raw(Json.Encode(Model))));
        editNotificationModel@(Model.Id).set('gridVisible',false);
        editNotificationModel@(Model.Id).set('editNotification@(Model.Id)',
            function () {
                var data = editNotificationModel@(Model.Id);
                if (!data.ContactData) {
                    alert("Contact Data Required");
                    return;
                }
                $.ajax({
                        url: '@Url.HttpRouteUrl("ActionApi",new{controller="Notifications", action= "Put" })',
                        method: 'PUT',
                        data: data.toWebAPIReadyJSON()
                    })
                    .done(function() {
                        @if (ViewBag.Callback != null)
                    {
                        @ViewBag.Callback@:();
                    }
                    }).fail(function() {
                        alert('SomethingWentWrong');
                    });
            });
        editNotificationModel@(Model.Id).set('notificationTypes',
            new kendo.data.DataSource({
                transport: {
                    read: {
                        url: '@Url.HttpRouteUrl("ActionApi",new { controller= "NotificationTypes", action="GetAll"})'
                    }
                }
            }));
        editNotificationModel@(Model.Id).set('notificationMethods',
            new kendo.data.DataSource({
                transport: {
                    read: {
                        url: '@Url.HttpRouteUrl("ActionApi",new { controller= "NotificationMethods", action="GetAll"})'
                    }
                }
            }));
        kendo.bind($('#edit-notification-@Model.Id'), editNotificationModel@(Model.Id));
</script>

ServiceMonitor.Web/Views/Notification/_Notification.cshtml
@using ServiceMonitor.BL
<div id="gNotification@(Model)"></div>

<script type="text/x-kendo-template" id="gNotification-toolbar-template@(Model)">
    <button id="gNotification-add" class="k-button k-button-icontext" onclick="notificationModel@(Model).addNotification()"><span class="k-icon k-i-plus"></span> Add</button>
</script>
<script type="text/x-kendo-template" id="gNotification-detail-template@(Model)">
    <div class="tabstrip"></div>
</script>


<script>

        var notificationModel@(Model) = function() {

            var refreshingNotification = function() {
                $("#gNotification@(Model)").data('kendoGrid').dataSource.read();
            }

            var closeAddNotification = function() {
                $('#add-notification').data('kendoWindow').close();
            }

            var addNotification = function() {
                $("<div/>").attr('id', 'add-notification').kendoWindow({
                    width: 850,
                    height: 600,
                    title: 'Add Notification',
                    modal: true,
                    actions: ["Close"],
                    content: '@Url.Action("_Add", "Notification")?id=@(Model)&callback=notificationModel@(Model).closeAddNotification',
                    close: function(e) {
                        e.sender.destroy();
                        refreshingNotification();
                    }
                }).data("kendoWindow").center().open();
            }

            var notificationDetailInit = function(e) {
                var detailRow = e.detailRow;
                var handler = detailRow.find(".tabstrip").kendoTabStrip({
                    animation: {
                        open: { effects: "fade:in", duration: 200 },
                        close: { effects: "fade:out", duration: 200 }
                    },
                    dataTextField: 'Name',
                    dataContentUrlField: 'url',
                    dataSource: [
                        { Name: "General", url: '@Url.Action("_Edit", "Notification")/' +
                            e.data.Id +
                            '?callback=notificationModel@(Model).refreshingNotification'
                        }
                    ]
                }).data('kendoTabStrip');
                handler.select(0);
            }

            var initNotification = function() {
                $("#gNotification@(Model)").kendoGrid({
                    dataSource: {
                        transport: {
                            read: {
                                url:
                                    "@Url.HttpRouteUrl("ActionApi", new {controller = "Notifications", action = "Get"})/@(Model)",
                            }
                        },
                        pageSize: 20,
                        schema: {
                            model: {
                                id: "Id",
                                fields: {
                                    Id: { type: "number", defaultValue: 0, editable: false },
                                    NotificationTypeId: { type: "number" },
                                    NotificationMethordId: { type: "number" },
                                    ContactData: { type: "string" },
                                }
                            }
                        }
                    },
                    selectable: true,
                    autoBind: true,
                    toolbar: kendo.template($("#gNotification-toolbar-template@(Model)").html()),
                    detailTemplate: kendo.template($("#gNotification-detail-template@(Model)").html()),
                    detailInit: notificationDetailInit,
                    pageable: {
                        pageSize: 20,
                        refresh: true
                    },
                    columns: [
                        {
                            field: "NotificationTypeId",
                            width: "150px",
                            title:"Notification Type",
                            values: @Html.Raw(Json.Encode(new NotificationTypeMgt().GetAll().Select(x => new { text=x.Name, value=x.Id })))
                        },
                        {
                            field: "NotificationMethodId",
                            width: "150px",
                            title: "Notification Method",
                            values: @Html.Raw(Json.Encode(new NotificationMethodMgt().GetAll().Select(x => new { text=x.Name, value=x.Id })))
                        },
                        { field: "ContactData"}
                    ]
                });
            }
            return {
                init: function() {
                    initNotification();
                },
                refreshingNotification: refreshingNotification,
                addNotification: addNotification,
                closeAddNotification: closeAddNotification
            }
        }();

        $(document).ready(function() {
            notificationModel@(Model).init();
        });

</script>

ServiceMonitor.Web/Views/Service/Index.cshtml
@{
    ViewBag.Title = "Services";
}
<div id="gService"></div>

<script type="text/x-kendo-template" id="gService-toolbar-template">
    <button id="gService-add" class="k-button k-button-icontext" onclick="serviceModel.addService()"><span class="k-icon k-i-plus"></span> Add</button>
</script>
<script type="text/x-kendo-template" id="gService-detail-template">
    <div class="tabstrip"></div>
</script>

@section scripts
{
    <script>

        var serviceModel = function() {

            var refreshingService = function() {
                $("#gService").data('kendoGrid').dataSource.read();
            }

            var closeAddService = function() {
                $('#add-service').data('kendoWindow').close();
            }

            var addService = function() {
                $("<div/>").attr('id', 'add-service').kendoWindow({
                    width: 850,
                    height: 600,
                    title: 'Add Service',
                    modal: true,
                    actions: ["Close"],
                    content: '@Url.Action("_Add", "Service")?callback=serviceModel.closeAddService',
                    close: function(e) {
                        e.sender.destroy();
                        refreshingService();
                    }
                }).data("kendoWindow").center().open();
            }

            var serviceDetailInit = function(e) {
                var detailRow = e.detailRow;
                var handler = detailRow.find(".tabstrip").kendoTabStrip({
                    animation: {
                        open: { effects: "fade:in", duration: 200 },
                        close: { effects: "fade:out", duration: 200 }
                    },
                    dataTextField: 'Name',
                    dataContentUrlField: 'url',
                    dataSource: [
                        { Name: "General", url: '@Url.Action("_Edit", "Service")/' + e.data.Id + '?callback=serviceModel.refreshingService' },
                        { Name: "Notification", url: '@Url.Action("_Notification", "Notification")/' + e.data.Id + '?callback=serviceModel.refreshingService' },
                        { Name: "Service Outage", url: '@Url.Action("_ServiceOutage", "ServiceOutage")/' + e.data.Id + '?callback=serviceModel.refreshingService' }
                    ]
                }).data('kendoTabStrip');
                handler.select(0);
            }

            var initService = function() {
                $("#gService").kendoGrid({
                    dataSource: {
                        transport: {
                            read: {
                                url:
                                    "@Url.HttpRouteUrl("ActionApi", new {controller = "Services", action = "GetAll"})",
                            }
                        },
                        pageSize: 20,
                        schema: {
                            model: {
                                id: "Id",
                                fields: {
                                    Id: { type: "number", defaultValue: 0, editable: false },
                                    Name: { type: "string" },
                                    Description: { type: "string" },
                                    Host: { type: "string" },
                                    Port: { type: "number" },
                                    Frequency: { type: "number" },
                                    GraceTime: { type: "number" }
                                }
                            }
                        }
                    },
                    selectable: true,
                    autoBind: true,
                    toolbar: kendo.template($("#gService-toolbar-template").html()),
                    detailTemplate: kendo.template($("#gService-detail-template").html()),
                    detailInit: serviceDetailInit,
                    pageable: {
                        pageSize: 20,
                        refresh: true
                    },
                    columns: [
                        { field: "Name", width: "230px"},
                        { field: "Description"},
                        { field: "Host"},
                        { field: "Port"},
                        { field: "Frequency"},
                        { field: "GraceTime"}
                    ]
                });
            }
            return {
                init: function() {
                    initService();
                },
                refreshingService: refreshingService,
                addService: addService,
                closeAddService: closeAddService
            }
        }();

        $(document).ready(function() {
            serviceModel.init();
        });

    </script>
}

ServiceMonitor.Web/Views/Service/_Edit.cshtml
<div id="edit-service-@Model.Id">
    <div class="form-wrapper">
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Name</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: Name" class="k-textbox" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Description</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: Description" class="k-textbox" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Host</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: Host" class="k-textbox" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Port</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: Port" class="k-textbox" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Frequency</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: Frequency" class="k-textbox" />
                <label> Seconds</label>
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">GraceTime</label>
            <div class="col-md-12">
                <input type="text" data-bind="value: GraceTime" class="k-textbox" />
                <label> Seconds</label>
            </div>
        </div>
        <div class="row form-footer">
            <div>
                @Html.Action("_Delete", "Service", new {id = Model.Id, callback = ViewBag.Callback })
                <button class="k-button k-button-icontext" data-bind="events={click:editService@(Model.Id)}"><span class="k-icon k-i-save"></span>Update</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
        var editServiceModel@(Model.Id) = kendo.observable(@(Html.Raw(Json.Encode(Model))));
        editServiceModel@(Model.Id).set('gridVisible',false);
        editServiceModel@(Model.Id).set('editService@(Model.Id)',
            function () {
                var data = editServiceModel@(Model.Id);
                if (!data.Name) {
                    alert("Service Name Required");
                    return;
                }
                else if (!data.Host) {
                    alert("Service Host Required");
                    return;
                }
                else if (!data.Port) {
                    alert("Service Port Required");
                    return;
                }
                else if (!data.Frequency) {
                    alert("Service Frequency Required");
                    return;
                }
                else if (data.Frequency < 1) {
                    alert("Service Frequency Must Grater than zero");
                    return;
                }
                else if (data.GraceTime < 1) {
                    alert("Service GraceTime Must Grater than zero");
                    return;
                }
                $.ajax({
                        url: '@Url.HttpRouteUrl("ActionApi",new{controller="Services", action= "Put" })',
                        method: 'PUT',
                        data: data.toWebAPIReadyJSON()
                    })
                    .done(function() {
                        @if (ViewBag.Callback != null)
                    {
                        @ViewBag.Callback@:();
                    }
                    }).fail(function() {
                        alert('SomethingWentWrong');
                    });
            });

        kendo.bind($('#edit-service-@Model.Id'), editServiceModel@(Model.Id));
</script>

ServiceMonitor.Web/Views/ServiceOutage/_Edit.cshtml
<div id="edit-serviceOutage-@Model.Id">
    <div class="form-wrapper">
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Reason</label>
            <div class="col-md-12">
                <input type="text" data-bind="value:Reason" class="k-textbox" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">Start Date</label>
            <div class="col-md-12">
                <input data-role="datetimepicker" data-bind="value: StartDateTime" />
            </div>
        </div>
        <div class="row" style="margin-top: 5px;">
            <label class="col-md-12">End Date</label>
            <div class="col-md-12">
                <input data-role="datetimepicker" data-bind="value: EndDateTime" />
            </div>
        </div>
        <div class="row form-footer">
            <div>
                @Html.Action("_Delete", "ServiceOutage", new { id = Model.Id, callback = ViewBag.Callback })
                <button class="k-button k-button-icontext" data-bind="events={click:editServiceOutage@(Model.Id)}"><span class="k-icon k-i-save"></span>Update</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
        var editServiceOutageModel@(Model.Id) = kendo.observable(@(Html.Raw(Json.Encode(Model))));
        editServiceOutageModel@(Model.Id).set('gridVisible',false);
        editServiceOutageModel@(Model.Id).set('editServiceOutage@(Model.Id)',
            function () {
                var data = editServiceOutageModel@(Model.Id);
                if (!data.Reason) {
                    alert("Reason Required");
                    return;
                }
                $.ajax({
                        url: '@Url.HttpRouteUrl("ActionApi",new{controller="ServiceOutages", action= "Put" })',
                        method: 'PUT',
                        data: data.toWebAPIReadyJSON()
                    })
                    .done(function() {
                        @if (ViewBag.Callback != null)
                    {
                        @ViewBag.Callback@:();
                    }
                    }).fail(function() {
                        alert('SomethingWentWrong');
                    });
            });
        kendo.bind($('#edit-serviceOutage-@Model.Id'), editServiceOutageModel@(Model.Id));
</script>

ServiceMonitor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/kendo/kendo.common-material.min.css" rel="stylesheet" />
    <link href="~/Content/kendo/kendo.material.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-animation.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Service Monitor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Configuration", "Index", "Service")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/kendo/jquery.min.js"></script>
    <script src="~/Scripts/kendo/kendo.all.min.js"></script>
    <script src="~/Scripts/kendo/kendo.aspnetmvc.min.js"></script>
    <script src="~/Scripts/kendo/kendo.modernizr.custom.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/humanize-duration.js"></script>
    <script src="~/Scripts/kendo/utilities.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>